version: '3'

services:

  traefik:

    image: traefik:v3.1

    ports:
      - "443:443"
      #- "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/certs/

    environment:
      #- TRAEFIK_API_INSECURE=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_LOG_LEVEL=INFO
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443
      - TRAEFIK_PROVIDERS_FILE_FILENAME=/certs/dynamic-conf.yml
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`myteam.mycompany.com`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=oks:$$apr1$$FHIBLWUW$$BGmEQZHCrCyFlJpPjtRW4."

      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`myteam.mycompany.com`) && (PathPrefix(`/traefik`))"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth, dashboard_stripprefix"
      - "traefik.http.middlewares.dashboard_stripprefix.stripprefix.prefixes=/traefik,/traefik/"