# version: '3'

services:

  traefik:

    image: traefik:v3.1

    container_name: traefik
    restart: unless-stopped

    ports:
      - "443:443"
      - "8443:8443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/certs/
      # Sync container date and time with host
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_LOG_LEVEL=INFO
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_mattermostcallsudp_ADDRESS=:8443/udp
      #- TRAEFIK_ENTRYPOINTS_mattermostCallsUDP_REUSEPORT=true
      - TRAEFIK_ENTRYPOINTS_mattermostcallstcp_ADDRESS=:8443
      - TRAEFIK_ENTRYPOINTS_mattermostcallsudp_UDP_TIMEOUT=300
      # SSL certificates should copy into ./certs folder and describe in dynamic-conf.yml file.
      - TRAEFIK_PROVIDERS_FILE_FILENAME=/certs/dynamic-conf.yml
    
    labels:
      - "traefik.enable=true"
      # This section configure the traefik API access. (https://myteam.mycompany.com/api/version)
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`myteam.mycompany.com`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.middlewares=auth"
      # Adding basic auth for accessing the relative service. Username: oks | Password: oks123
      - "traefik.http.middlewares.auth.basicauth.users=oks:$$apr1$$FHIBLWUW$$BGmEQZHCrCyFlJpPjtRW4."
      # This section configures the Traefik dashboard. (https://myteam.mycompany.com/traefik/)
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`myteam.mycompany.com`) && (PathPrefix(`/traefik`))"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth, dashboard_stripprefix"
      - "traefik.http.middlewares.dashboard_stripprefix.stripprefix.prefixes=/traefik,/traefik/"